name: Fetch and Install
on:
  push:
    branches:
      - master
          

jobs:
  setup:
    uses: ./.github/workflows/fetch-install.yml


  testing:
    needs: setup
    runs-on: ubuntu-latest
    container: node:trixie
    steps:

      - name: fetch code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm ci

      - name: test the app
        run: npx vitest run src


  build:
    needs: testing
    runs-on: ubuntu-latest
    container: node:alpine
    steps:
      - name: fetch code
        uses: actions/checkout@v4

      - name: Download node-modules
        uses: actions/download-artifact@v5
        with:
          name: node_modules

      - name: Build 
        run: npm run build

      