name: Fetch and Install
on:
  push:
    branches:
      - master
          

jobs:
  setup:
    uses: ./.github/workflows/fetch-install.yml


  testing:
    needs: setup
    runs-on: ubuntu-latest
    container: node:trixie
    steps:

      - name: fetch code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm ci

      - name: test the app
        run: npx vitest run src


  build:
    needs: testing
    runs-on: ubuntu-latest
    container: node:alpine
    steps:
      - name: fetch code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v5
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci


      - name: Build 
        run: npm run build

      