name: Fetch and Install
on:
  push:
    branches:
      - master
          

jobs:
  setup:
    uses: ./.github/workflows/fetch-install.yml


  testing:
    needs: setup
    runs-on: ubuntu-latest
    container: node:trixie
    steps:

      - name: fetch code
        uses: actions/checkout@v4

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules

      - name: install dependencies
        run: npm ci

      - name: test the app
        run: npm run test
    # runs-on: ubuntu-latest
    # environment: testing

    # container:
    #   image: node:trixie


    # steps:
    #   - name: Fetch Code
    #     uses: actions/checkout@v4

    #   - name: Cache dependencies
    #     uses: actions/cache@v5
    #     id: cache-npm
    #     with:
    #       path: ~/.npm
    #       key: ${{ runner.os }}-key-${{ hashFiles('**/package-lock.json') }}

    #   - name: Install Dependencies
    #     if: steps.cache-npm.outputs.cache-hit != 'true'
    #     run: npm ci

      